# Generated by Django 3.2.23 on 2024-09-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producttbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakename', models.CharField(max_length=100)),
                ('cakeprice', models.IntegerField()),
                ('cakeimage', models.FileField(upload_to='pictures')),
                ('category', models.CharField(choices=[('wedding', 'wedding'), ('birthday', 'birthday'), ('anniversary', 'anniversary'), ('other', 'other')], default='other', max_length=100)),
            ],
        ),
    ]
